apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcemappings.v2v.kubevirt.io
spec:
  group: v2v.kubevirt.io
  names:
    kind: ResourceMapping
    listKind: ResourceMappingList
    plural: resourcemappings
    singular: resourcemapping
    categories:
    - all
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          description: 'ResourceMappingSpec defines the desired state of ResourceMapping'
          properties:
            ovirt:
              description: 'OvirtMappings defines the mappings of ovirt resources to kubevirt'
              properties:
                networkMappings:
                  type: array
                storageMappings:
                  type: array
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
