---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-with-vmware-credentials
type: Opaque
stringData:
  vmware: |-
    # API URL of the vCenter or ESXi host
    apiUrl: "https://my.vcenter.example.com/sdk"
    # Username provided in the format of username@domain.
    username: administrator@vsphere.local
    password: 123456
    # The SHA-1 certificate thumbprint of the vCenter or ESXi host, in colon-separated hexidecimal octets.
    thumbprint: 21:EA:74:11:59:89:5E:20:D5:D9:A2:39:5C:6A:2D:36:38:B2:52:2B