apiVersion: v2v.kubevirt.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: vmimport-example
  namespace: default
spec:
  providerCredentialsSecret:
    name: my-secret-with-vmware-credentials
    namespace: default
  targetVmName: examplevm
  startVm: true
  source:
    vmware:
      vm:
        id: 42253ce0-5f76-918d-d85c-d7506f7cc056 # VirtualMachine UUID
        # name: my-vm-name
      mappings:
        networkMappings:
          - source:
              name: VM Network
            target:
              name: pod
            type: pod
        storageMappings:
          - source:
              id: datastore-13 # Datastore Managed Object Reference
            target:
              name: storage_class_1
        diskMappings: # specifies per-disk placement on storage class, overriding the datastore mapping
          - source:
              name: Hard disk 1 # VirtualDisk name
            target:
              name: storage_class_2

# The VirtualMachine can be identified either by its UUID, or by its name. Its UUID can be retrieved
# via the vSphere SDK, or from the vCenter Flash client. To find the UUID in the UI, find the Host
# containing the VM you want, choose the VMs tab, and then right click on the columns.
# From the dropdown choose "Show/Hide Columns", and then check the box for "UUID".
