apiVersion: v2v.kubevirt.io/v1alpha1
kind: ResourceMapping
metadata:
  name: example-resourcemappings
  namespace: example-ns
spec:
  ovirt:
    networkMappings:
      - source:
          name: red/profile1  # maps of ovirt 'logic network/vnic profile' to network attachment definition
        target:
          name: xyz
        type: multus
      - source:
          name: ovirtmgmt/ovirtmgmt # maps of 'ovirtmgmt' vnic-profile of 'ovirtmgmt' network to pod's network
        target:
          name: pod
        type: pod
    storageMappings:
      - source:
          name: ovirt_storage_domain_1 # maps ovirt storage domain to storage class
        target:
          name: storage_class_1
