---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-with-ovirt-credentials
  namespace: default
type: Opaque
stringData:
  ovirt: |
    apiUrl: "https://my.ovirt-engine-server/ovirt-engine/api"
    username: admin@internal # provided in the format of username@domain
    password: 123456
    ca.cert: |  # The certificate presented by the server will be verified using these CA certificates.
                # If not set, system wide CA certificate store is used.
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----


