apiVersion: v2v.kubevirt.io/v1alpha1
kind: VirtualMachineImport
metadata:
  name: vmimport-example
  namespace: default
spec:
  providerCredentialsSecret: # A secret holding the access credentials to ovirt, see example secret.yaml
    name: my-secret-with-ovirt-credentials
    namespace: default # optional, if not specified, use CR's namespace
  resourceMapping:
    name: example # a mapping of ovirt resource (network, storage)
    namespace: default # optional, if not specified, use CR's namespace
  targetVmName: examplevm # The target name is optional. If not provided, the import will attempt to use the origin name of the VM or to normalize it.
  startVm: true # should the vm be started after the vm was created on kubevirt
  source:
    ovirt:  # represents ovirt-engine to import from the virtual machine
      vm: # in order to uniquely identify vm on ovirt with need to provide (vm_name,cluster) or use (vm-id)
        id: 80554327-0569-496b-bdeb-fcbbf52b827b
      mappings: # mapping section overrides mapping rules provided by 'resourceMapping' external mapping resource
        networkMappings:
          - source:
              name: red/profile1 # maps of ovirt 'logic network/vnic profile' to network attachment definition
            target:
              name: pod
            type: pod
        storageMappings:
          - source:
              name: storage_domain_1
            target:
              name: storage_class_1
        diskMappings: # specifies per-disk placement on storage class
          - source:
              id: 8181ecc1-5db8-4193-9c92-3ddab3be7b05
            target:
              name: storage_class_1
